# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'rev01'

target 'rev01' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rev01

end

target 'rev01-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rev01-tvOS

end
